config/routes.rb
ForumDemo::Application.routes.draw do
  devise_for :users

  resources :boards do
    resources :posts
  end

  namespace :admin do
    resources :boards do
      resources :posts
    end
  end

end

app/models/board.rb
class Board < ActiveRecord::Base
	has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :board, :counter_cache => true
  belongs_to :user
  #default_scope :order => "created_at DESC"
  scope :recent, :order => "updated_at DESC"

  #fileuploader
  mount_uploader :avatar, AvatarUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  def is_admin?
    is_admin
  end

  attr_protected :is_admin
end

app/controllers/admin/boards_controller.rb
class Admin::BoardsController < ApplicationController
	layout "admin"
	before_filter :require_is_admin


	def index
		@boards = Board.all
	end

	def new
		@board = Board.new
	end

	def edit
		@board = Board.find(params[:id])
	end

	def create
		@board = Board.new(params[:board])

		if @board.save
			redirect_to board_path(@board)
		else
			render :action => "new"
		end
	end

	def update
		@board = Board.find(params[:id])

		if @board.update_attributes(params[:board])
			redirect_to rboard_path(@board)
		else
			render :action => "edit"
		end
	end

	def destroy
		@board = Board.find(params[:id])
		@board.destroy

		redirect_to admin_boards_url
	end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout "admin"
  before_filter :require_is_admin
  before_filter :authenticate_user!, :except => [:index]
  before_filter :find_board_post


  def edit
   
  end

  def update

    if @post.update_attributes(params[:post])
      redirect_to board_post_path(@board, @post)
    else
      render action: "edit"
    end
  end

  def destroy
    @post.destroy

    redirect_to board_posts_path(@board)
  end

  protected
    def find_board_post
      @board = Board.find(params[:board_id])
      @post = @board.posts.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def require_is_admin
    unless (current_user && current_user.is_admin?)
      flash[:alert] = "You must be admin!"
      redirect_to root_path
    end
  end
  
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

	def index
		@boards = Board.all
	end

	def show
		@board = Board.find(params[:id])
		@posts = @board.posts.recent.paginate(:page => params[:page], :per_page => 5)
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :find_board


  def index
  	redirect_to board_path(@board)
  end

  def show
    @post = @board.posts.find(params[:id])
  end

  def new
    @post = @board.posts.build
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def create
    @post = @board.posts.build(params[:post])
    @post.user_id = current_user.id

    if @post.save
      redirect_to board_post_path(@board, @post)
    else
      render :action => "new"
    end
  end

  def update
    @post = current_user.posts.find(params[:id])

    if @post.update_attributes(params[:post])
      redirect_to board_post_path(@board, @post)
    else
      render :action => "edit"
    end
  end

  def destroy
  	@post = current_user.posts.find(params[:id])
    @post.destroy

    redirect_to board_posts_path(@board)
  end

  protected
    def find_board
      @board = Board.find(params[:board_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/boards/_form.html.erb
	<div class = "field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class = "action">
		<%= f.submit %>
	</div>

app/views/admin/boards/edit.html.erb
<h1>Edit Board</h1>

<%= form_for @board, :url => admin_board_path(@board) do |f| %>
<%= render :partial => "form", :locals => {:f => f} %>
<% end %>

<%= link_to("Show", @board) %> |
<%= link_to("Back", admin_boards_path) %>

app/views/admin/boards/index.html.erb
<h1>Listing Board</h1>

<table>
	<tr>
		<th>Name</th>
		<th></th>
		<th></th>
		<th></th>
	<% @boards.each do |board| %>
		<tr>
			<td><%= board.name %></td>
			<td><%= link_to("Show", board)%></td>
			<td><%= link_to("Edit", edit_board_path(board)) %></td>
			<td><%= link_to("Destroy", board, :confirm => "Are you sure?", :method => :delete) %></td>
		</tr>
	<% end %>
</table>

<br/>

<%= link_to("New Board", new_board_path) %>

app/views/admin/boards/new.html.erb
<h1>New Board</h1>

<%= form_for @board, :url => admin_boards_path do |f| %>
<%= render :partial => "form", :locals => { :f => f} %>
<% end %>

<%= link_to("Back", admin_boards_path) %>

app/views/admin/posts/_form.html.erb
  <div>
    <%= f.label :title, "title" %>
    <%= f.text_field :title %>
    <%= f.label :content, "Content" %>
    <%= f.text_area :content %>
  </div>
  <div>
    <%= f.submit "Create" %>
  </div>

app/views/admin/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_for @post, :url => admin_board_post_path(@board, @post) do |f| %>
<%= render :partial => "form", :locals => {:f => f} %>
<% end %>

<%= link_to("Show", board_post_path(@board, @post)) %> |
<%= link_to("Back", board_posts_path(@board)) %>

app/views/admin/posts/index.html.erb
<h1>Listing Post</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @posts.each do |post| %>
    <tr>
      <td><%= board.title %></td>
      <td><%= link_to("Show", post_path(post)) %></td>
      <td><%= link_to("Edit", edit_post_path(post)) %></td>
      <td><%= link_to("Destroy", post_path(post),:confirm => "Are you sure?", :method => :delete) %></td>
    </tr>
  <% end %>
</table>

<% link_to("New post", new_post_path) %>

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
	<div class = "field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class = "action">
		<%= f.submit %>
	</div>
<% end %>

app/views/boards/index.html.erb
<h1>Listing Board</h1>

<table>
	<tr>
		<th>Name</th>
		<th></th>
		<th></th>
		<th></th>
	<% @boards.each do |board| %>
		<tr>
			<td><%= board.name %></td>
			<td><%= link_to("Show", board) %></td>
			<% if current_user && current_user.is_admin? %>
			<td><%= link_to("A-Edit", edit_admin_board_path(board)) %></td>
			<td><%= link_to("A-Destroy", admin_boards_path, :confirm => "Are you sure?", :method => :delete) %></td>
			<% end %>
		</tr>
	<% end %>
</table>

<br/>
<% if current_user && current_user.is_admin? %>
<%= link_to("A-New Board", new_admin_board_path) %>
<% end %>

app/views/boards/show.html.erb
<p id = "notice"><%= notice %></p>

<p>
	<b>Name:</b>
	<%= @board.name %>
</p>

<h1>Listing posts - Total <%= @board.posts.size %></h1>

<table>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Content</th>
    <th>Created At</th>
    <th>Updated At</th>
    <th></th>
    <th></th>
  </tr>
  <% @posts.each do |post| %>
  <tr>
    <td><%= post.id %></td>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= l(post.created_at, :format => :short) %></td>
    <td><%= l(post.updated_at, :format => :short) %></td>
    <td><%= link_to("Show", board_post_path(@board, post)) %></td>
    <% if current_user && post.user == current_user %>
    <td><%= link_to("Edit", edit_board_post_path(@board, post)) %></td>
    <td><%= link_to("Destroy", board_post_path(@board, post), :confirm => "Are you sure?", :method => :delete) %></td>
    <% end %>

    <% if current_user && current_user.is_admin? %>
    <td><%= link_to("A-Edit", edit_admin_board_post_path(@board, post)) %></td>
    <td><%= link_to("A-Destroy", admin_board_post_path(@board, post), :confirm => "Are you sure?", :method => :delete) %></td>
    <% end %>
  </tr>
  <% end %>
</table>
<%= will_paginate(@posts) %>
<br/>

<%= link_to("New Post", new_board_post_path(@board)) %> | 
<% if current_user && current_user.is_admin? %>
<%= link_to("A-Edit", edit_admin_board_path(@board)) %> |
<% end %>
<%= link_to("Back", boards_path) %>

app/views/common/_user_nav.erb
<div class = "user_navigation">
  <% if user_signed_in? %>
  Hi! <%= current_user.email %>
  <%= link_to("Sign out", destroy_user_session_path, :method => :delete) %>
  <% if current_user && current_user.is_admin? %>
  <%= link_to("Admin Panel", admin_boards_path) %>
  <% end %>
  <% else %>
  <%= link_to("Sign in", new_user_session_path) %>
  <%= link_to("Sign up", new_user_registration_path) %>
  <% end %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ForumDemo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1> Admin Panel </h1>
<%= render :partial => "common/user_nav" %>
<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ForumDemo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial => "common/user_nav" %>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
  <div>
    <%= f.label :title, "title" %>
    <%= f.text_field :title %>
    <%= f.label :content, "Content" %>
    <%= f.text_area :content %>
    <p>Upload a picture</p>
    <%= image_tag(@post.avatar_url) if @post.avatar? %>
    <%= f.file_field :avatar %>
    <%= f.hidden_field :avatar_cache %>
    <p>Or, you can upload a image url...</p>
    <%= f.text_field :remote_avatar_url %>
  </div>
  <div>
    <%= f.submit "Create" %>
  </div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_for @post, :url => board_posts_path(@board) do |f| %>
<%= render :partial => "form", :locals => {:f => f} %>
<% end %>

<%= link_to("Show", board_post_path(@board, @post)) %> |
<%= link_to("Back", board_posts_path(@board)) %>

app/views/posts/index.html.erb
<h1>Listing Post</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @posts.each do |post| %>
    <tr>
      <td><%= board.title %></td>
      <td><%= link_to("Show", board_post_path(@board, post)) %></td>
      <td><%= link_to("Edit", edit_board_post_path(@board, post)) %></td>
      <td><%= link_to("Destroy", board_post_path(@board, post),:confirm => "Are you sure?", :method => :delete) %></td>
    </tr>
  <% end %>
</table>

<%= link_to("New post", new_board_post_path(@board)) %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for @post, :url => board_posts_path(@board), :html => {:multipart => true} do |f| %>
<%= render :partial => "form", :locals => {:f => f} %>
<% end %>

<%= link_to("Back", board_posts_path(@board)) %>

app/views/posts/show.html.erb
<p>
  <b>Title: <%= @post.title %></b><hr/>
  <%= image_tag(@post.avatar_url) if @post.avatar? %><br/>
  <%= @post.content %>
</p>

<% if current_user && @post.user == current_user %>
<%= link_to("Edit", edit_board_post_path(@board, @post)) %> |
<% end %>

<% if current_user && current_user.is_admin? %>
<%= link_to("A-Edit", edit_admin_board_post_path(@board, @post)) %> |
<% end %>

<%= link_to("Back", board_posts_path(@board)) %>